[org/gnome/shell/extensions/lockkeys]
capslock-indicator='when-active'
capslock-notification='osd'
notification-preferences='off'
numlock-indicator='never'
numlock-notification='off'
style='show-hide-capslock'

