schema_version: 1
name: file-sync
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: file-sync
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
