#!/bin/bash
# Generated by tools/vendor_upstream.py from the upstream PrebuildCommand list.
# Runs inside upstream/ at build time (tools/build_packages.py); ARCH and SUITE are set.
set -euo pipefail
cd "$(dirname "$0")/upstream"
for f in obj/$ARCH/usr/bin/add-apt-repository; do sed -i '/self.distro = get_distro()/a \        self.distro.id = '\''ubuntu'\'' # Patched by SynOS' "$f"; done
for d in obj/$ARCH; do mkdir -p "$d/usr/share/python-apt/templates" "$d/usr/share/distro-info" && ln -sf ubuntu.info "$d/usr/share/python-apt/templates/synos.info" && ln -sf ubuntu.csv "$d/usr/share/distro-info/synos.csv"; done
