schema_version: 1
name: container-management
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: container-management
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
