schema_version: 1
name: couchdb-server
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: couchdb-server
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
