schema_version: 1
name: authoritative-dns
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: authoritative-dns
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
