schema_version: 1
name: kubernetes-server
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: kubernetes-server
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
