schema_version: 1
name: object-storage
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: object-storage
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
