schema_version: 1
name: yocto-builder-docs
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: yocto-builder-docs
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
