schema_version: 1
name: web-server-apache
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: web-server-apache
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
