[org/gnome/shell/extensions/simple-weather]
always-packaged-icons=false
is-activated=true
my-loc-provider='disable'
panel-box='left'
secondary-panel-detail='conditionText'
show-panel-icon=true
show-suntime=false
symbolic-icons-panel=true
