schema_version: 1
name: test-engine
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: test-engine
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
