"""Generate persistent storage configuration inside the mounted target."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .btrfs import BTRFS_SUBVOLUMES
from .command import CommandRunner
from .model import Filesystem
from .steps import FailurePolicy, InstallContext


@dataclass
class ConfigureStorageStep:
    runner: CommandRunner
    id: str = "configure-storage"
    title: str = "Configure persistent filesystems and swap"
    failure_policy: FailurePolicy = FailurePolicy.FATAL
    progress_weight: int = 2
    destructive: bool = False

    def preflight(self, context: InstallContext) -> None:
        self.runner.require_commands(("blkid",))

    def execute(self, context: InstallContext) -> None:
        target = _target(context)
        devices = context.values["partition_devices"]
        uuids = {
            name: self.runner.run(
                ("blkid", "-s", "UUID", "-o", "value", device),
                timeout=10,
            ).stdout.strip()
            for name, device in devices.items()
            if name in {"root", "efi-system", "swap"}
        }
        missing = sorted(name for name, value in uuids.items() if not value)
        if missing:
            raise RuntimeError(
                "Missing filesystem UUID: " + ", ".join(missing)
            )

        if context.plan.storage.filesystem is Filesystem.BTRFS:
            root_lines = "".join(
                f"UUID={uuids['root']} {subvolume.mount_point} btrfs "
                f"{subvolume.mount_options} 0 0\n"
                for subvolume in BTRFS_SUBVOLUMES
            )
        else:
            filesystem = context.plan.storage.filesystem
            pass_number = 0 if filesystem is Filesystem.XFS else 1
            root_lines = (
                f"UUID={uuids['root']} / {filesystem.value} "
                f"defaults,noatime 0 {pass_number}\n"
            )

        swap_line = (
            f"UUID={uuids['swap']} none swap "
            f"sw,pri={context.plan.swap.disk_priority} 0 0\n"
            if "swap" in uuids
            else ""
        )
        fstab = (
            "# /etc/fstab generated by SynOS Installer\n"
            f"{root_lines}"
            f"UUID={uuids['efi-system']} /boot/efi vfat defaults,noatime 0 1\n"
            f"{swap_line}"
        )
        etc = target / "etc"
        etc.mkdir(parents=True, exist_ok=True)
        (etc / "fstab").write_text(fstab, encoding="utf-8")

        # Keep zram declarative and explicit. This is the format consumed by
        # synos-swap-config; omitting a fixed size preserves 50%-of-RAM.
        defaults = etc / "default"
        defaults.mkdir(parents=True, exist_ok=True)
        (defaults / "synos-zram").write_text(
            "ZRAM_ENABLED=yes\n"
            f"ZRAM_ALGORITHM={context.plan.swap.zram_algorithm}\n"
            f"ZRAM_PRIORITY={context.plan.swap.zram_priority}\n",
            encoding="utf-8",
        )

    def verify(self, context: InstallContext) -> None:
        target = _target(context)
        fstab = (target / "etc/fstab").read_text(encoding="utf-8")
        required = ["/boot/efi vfat", "UUID=", " / "]
        if context.plan.storage.swap_size_mib:
            required.append(" none swap ")
        missing = [value for value in required if value not in fstab]
        if missing:
            raise RuntimeError("Generated fstab failed verification")
        if context.plan.storage.swap_size_mib and (
            f"pri={context.plan.swap.disk_priority}" not in fstab
        ):
            raise RuntimeError("Disk swap priority is missing from fstab")
        if not context.plan.storage.swap_size_mib and " none swap " in fstab:
            raise RuntimeError("Unexpected disk swap entry in fstab")
        zram = (target / "etc/default/synos-zram").read_text(
            encoding="utf-8"
        )
        required_zram = (
            "ZRAM_ENABLED=yes",
            f"ZRAM_ALGORITHM={context.plan.swap.zram_algorithm}",
            f"ZRAM_PRIORITY={context.plan.swap.zram_priority}",
        )
        if any(value not in zram for value in required_zram):
            raise RuntimeError("Generated zram configuration failed verification")

    def cleanup(self, context: InstallContext) -> None:
        return None


def _target(context: InstallContext) -> Path:
    target = context.values.get("target")
    if not isinstance(target, Path):
        raise RuntimeError("Target filesystem is not mounted")
    return target
