schema_version: 1
name: digital-signage
version: 1.0.0

base: ubuntu
suite: noble
arch: amd64

profile: digital-signage
regions: [us]
brand: synos

mirrors: {}

packages:
  repository: ""
  takeover: all

overrides: {}
