#!/bin/bash
# Generated by tools/vendor_upstream.py from the upstream PrebuildCommand list.
# Runs inside upstream/ at build time (tools/build_packages.py); ARCH and SUITE are set.
set -euo pipefail
cd "$(dirname "$0")/upstream"
bash scripts/download-model.sh
bash scripts/download-vad-model.sh
