#!/bin/bash
# Generated by tools/vendor_upstream.py from the upstream PrebuildCommand list.
# Runs inside upstream/ at build time (tools/build_packages.py); ARCH and SUITE are set.
set -euo pipefail
cd "$(dirname "$0")/upstream"
for src in obj/$ARCH/usr/share/plymouth/themes/spinner; do cp -r "$src" "$(dirname "$src")/synos-spinner"; done
for f in obj/$ARCH/usr/share/plymouth/themes/synos-spinner/spinner.plymouth; do mv "$f" "$(dirname "$f")/synos-spinner.plymouth"; done
sed -i 's|themes//spinner|themes/synos-spinner|g; s|themes/spinner|themes/synos-spinner|g; s|Name=Spinner|Name=SynOS Spinner|g' obj/$ARCH/usr/share/plymouth/themes/synos-spinner/synos-spinner.plymouth
sed -i '/^MessageBelowAnimation=true$/a DialogClearsFirmwareBackground=false' obj/$ARCH/usr/share/plymouth/themes/synos-spinner/synos-spinner.plymouth
sed -i '/^UseEndAnimation=false$/a UseFirmwareBackground=true' obj/$ARCH/usr/share/plymouth/themes/synos-spinner/synos-spinner.plymouth
rm -f  obj/$ARCH/usr/share/plymouth/ubuntu-logo.png
rm -rf obj/$ARCH/usr/share/plymouth/themes/spinner
find obj/$ARCH/usr/share/plymouth/themes/synos-spinner -name 'watermark.png' -type l -delete
